name: vit-shapley
channels:
  - pytorch
  - fastai
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20230802.0
  - absl-py=2.1.0
  - annotated-types=0.6.0
  - asttokens=2.4.1
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.32.2
  - ca-certificates=2024.7.4
  - catalogue=2.0.10
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=7.1.2
  - cloudpathlib=0.16.0
  - colorama=0.4.6
  - comm=0.2.2
  - confection=0.1.4
  - configparser=7.0.0
  - contourpy=1.2.1
  - cudatoolkit=11.1.1
  - cycler=0.11.0
  - cymem=2.0.6
  - cython-blis=0.7.9
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.8.2
  - decorator=5.1.1
  - docker-pycreds=0.4.0
  - docopt=0.6.2
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - fastai=2.5.3
  - fastcore=1.3.29
  - fastdownload=0.0.7
  - fastprogress=1.0.3
  - ffmpeg=4.3
  - filelock=3.15.4
  - fontconfig=2.14.2
  - fonttools=4.53.1
  - freetype=2.12.1
  - fsspec=2024.6.1
  - future=1.0.0
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glib=2.80.2
  - glib-tools=2.80.2
  - gmp=6.3.0
  - gnutls=3.6.13
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gtest=1.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - huggingface_hub=0.23.4
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - importlib-metadata=8.0.0
  - importlib-resources=6.4.0
  - importlib_metadata=8.0.0
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - ipdb=0.13.9
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jbig=2.1
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - jsonpickle=1.5.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - langcodes=3.3.0
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=2.2.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.3.3
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgcc-ng=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.2
  - libgomp=14.1.0
  - libhwloc=2.11.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnsl=2.0.1
  - libpng=1.6.43
  - libpq=12.17
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libstdcxx-ng=14.1.0
  - libtiff=4.3.0
  - libuuid=2.38.1
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.13.1
  - libzlib=1.2.13
  - lz4-c=1.9.3
  - markdown=3.6
  - markdown-it-py=2.2.0
  - markupsafe=2.1.5
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - munch=2.5.0
  - munkres=1.1.4
  - murmurhash=1.0.7
  - mysql=5.7.20
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - nettle=3.6
  - numpy=1.26.4
  - olefile=0.47
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.3.1
  - packaging=24.1
  - pandas=1.4.0
  - parso=0.8.4
  - pathtools=0.1.2
  - pathy=0.10.2
  - patsy=0.5.6
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=24.0
  - platformdirs=4.2.2
  - preshed=3.0.6
  - promise=2.3
  - prompt-toolkit=3.0.47
  - protobuf=3.20.3
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - pybind11-abi=4
  - pycparser=2.22
  - pydantic=2.5.3
  - pydantic-core=2.14.6
  - pydeprecate=0.3.2
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.9.0
  - python_abi=3.9
  - pytorch=1.10.2
  - pytorch-lightning=1.5.9
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - qhull=2020.2
  - qt-main=5.15.2
  - re2=2022.04.01
  - readline=8.2
  - regex=2024.5.15
  - requests=2.32.3
  - rich=13.7.1
  - sacred=0.8.2
  - sacremoses=0.0.53
  - scikit-learn=1.4.2
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - sentry-sdk=2.10.0
  - setuptools=59.5.0
  - shellingham=1.5.0.post1
  - shortuuid=1.0.13
  - sip=6.5.1
  - six=1.16.0
  - smart_open=5.2.1
  - smmap=5.0.0
  - spacy=3.7.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - sqlite=3.45.3
  - srsly=2.4.8
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - subprocess32=3.5.4
  - tbb=2021.12.0
  - tensorboard=2.17.0
  - tensorboard-data-server=0.7.0
  - termcolor=2.4.0
  - thinc=8.2.2
  - threadpoolctl=3.5.0
  - timm=0.5.4
  - tk=8.6.14
  - tokenizers=0.10.3
  - toml=0.10.2
  - torchmetrics=0.7.0
  - torchvision=0.11.3
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - transformers=4.16.2
  - ttach=0.0.3
  - typer=0.9.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - wandb=0.12.10
  - wasabi=0.9.1
  - wcwidth=0.2.13
  - weasel=0.3.4
  - werkzeug=3.0.3
  - wheel=0.43.0
  - wrapt=1.16.0
  - xkeyboard-config=2.42
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yaml=0.2.5
  - yaspin=2.2.0
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.6
  - pip:
      - captum==0.5.0
      - einops==0.8.0
      - opencv-python==4.6.0.66
